// Generated by CoffeeScript 1.8.0
(function() {
  var assert, expect;

  assert = this.chai.assert;

  expect = this.chai.expect;

  this.makeTests(assert, expect, btoa, this.Octokit);

  if (this.PHANTOMJS) {
    this.blanket.options('reporter', '../node_modules/grunt-blanket-mocha/support/grunt-reporter.js');
  }

  mocha.checkLeaks();

  mocha.globals(['jQuery']);

  mocha.run();

}).call(this);
