// Generated by CoffeeScript 1.8.0
(function() {
  var Octokit, assert, btoa, chai, expect, makeTests;

  chai = require('chai');

  Octokit = require('../octokit')["new"];

  makeTests = require('./common').makeTests;

  assert = chai.assert;

  expect = chai.expect;

  btoa = function(str) {
    var buffer;
    buffer = new Buffer(str, 'binary');
    return buffer.toString('base64');
  };

  makeTests(assert, expect, btoa, Octokit);

}).call(this);
